### PR TITLE
Fix issue with newlines in plain strings without markdown formatting

### PR DESCRIPTION
**Pull request by juliushaertl**

### CODE REVIEW

**Comment by juliushaertl** [comment]
First commit test runs should fail

**Comment by juliushaertl** [comment]
With markdown support disabled there was an infinite loop cased by line breaks not being handled properly. This was fixed with allowing blankLine block elements: https://github.com/juliushaertl/vue-richtext/pull/286/commits/5c7b82942d5eaea7db86d1c19c7cc0e94a19356c

Now the remaining issue is that line breaks are always being converted to paragraphs. I've added https://github.com/remarkjs/remark-breaks to preserve breaking lines, however it seems that there is some conflict with the remark-disable-tokenizers plugin.

I figured out that when the noop tokenizer returns false this magically solves the issue, but I'm unsure why this would even work. I didn't see the return value of that being used anywhere when stepping through the code for some time.

Relevant change:
https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-disable-tokenizers/src/index.js#L3

Failure with default remark-disable-tokenizers:
image

Expected with patched remark-disable-tokenizers in e9bdf61:

image

I have the feeling that this is a valid fix for the remark-disabled-tokenizers plugin as according to https://github.com/mattcreager/remark-parse#function-tokenizereat-value-silent I would expect that the return value of the noop tokenizer should always be false:

> Returns
> - In silent mode, whether a node can be found at the start of value;
> - In normal mode, a node if it can be found at the start of value.


@Cacodaimon Since you are probably a bit more into the remark, mind to have a look if my change makes sense? Maybe you have any idea where this goes wrong.

**Comment by Cacodaimon** [comment]
@juliushaertl Sure I will take a look at this this evening.

**Comment by Cacodaimon** [comment]
I checked the code, I believe that when a tokenizer returns a `falsy` value e.g. https://github.com/juliushaertl/vue-richtext/blob/eb0fab966d644a2ca4541e7bbf0c0e0ae7abb5e3/src/RichText.vue#L42 it means there was no match and if it returns `true` e.g. https://github.com/juliushaertl/vue-richtext/blob/eb0fab966d644a2ca4541e7bbf0c0e0ae7abb5e3/src/RichText.vue#L46 it means "I mached but I have to be silent". Both results to be not rendered. The origin noop return value seems wrong to me, hence each disabled tokenizer gets replaced with one returning always *silent*, even if the parser did not used the flag.

From here on i can only play oracle... but if the **break** is the child of another block, which is *silent*, the children might not be traversed, too.

**Pull request merged**
